<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\InsuranceApp.Application\InsuranceApp.Application.csproj" />
    <ProjectReference Include="..\InsuranceApp.Infrastructure\InsuranceApp.Infrastructure.csproj" />
    <ProjectReference Include="..\InsuranceApp.Contracts\InsuranceApp.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
